name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v -o landrun ./cmd/landrun/main.go

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: landrun
          path: ./landrun

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
